<script setup lang="ts">
import { computed, ref } from 'vue'
import CButton from './CButton.vue'

import { useChatGPTSetting } from '../store'

const props = defineProps<{
  open: boolean
}>()

const emit = defineEmits<(e: 'update:open', value: boolean) => void>()

const store = useChatGPTSetting()

const supportedModels = ['gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-4']

const maxTokensRange = computed(() => {
  if (store.model === 'gpt-3.5-turbo-16k') {
    return 16384
  } else if (store.model === 'gpt-4') {
    return 8192
  }

  return 4096
})

const dialog = ref<HTMLDialogElement>()

const close = (): void => {
  emit('update:open', false)
}
</script>
<template>
  <dialog
    ref="dialog"
    @close="$emit('update:open', false)"
    :open="props.open"
    class="border border-blue-100 rounded-md p-4 drop-shadow-md max-h-screen overflow-auto"
  >
    <div class="flex flex-col gap-3">
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>Model</p>
          <p class="text-gray-600 text-sm">The model to use for the AI</p>
        </div>
        <select
          :value="store.model"
          @change="(e) => store.setModel((e.target as HTMLSelectElement).value)"
          class="bg-white border border-blue-300 text-blue-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-3"
        >
          <option v-for="model in supportedModels" :key="model" :value="model">
            {{ model }}
          </option>
        </select>
      </div>
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>System</p>
          <p class="text-gray-600 text-sm">Use this to direct the dialogs</p>
        </div>
        <textarea
          v-model="store.system"
          class="w-full min-h-[200px] rounded-md border border-blue-100 outline-blue-200 px-3 py-2"
        ></textarea>
      </div>
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>Temperature</p>
          <p class="text-gray-600 text-sm">
            The higher the temperature, the crazier the text
          </p>
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model.number="store.temperature"
            type="range"
            min="0"
            max="2"
            step="0.01"
            class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
          />
          <input
            v-model="store.temperature"
            type="number"
            class="w-20 rounded-md border border-blue-100 outline-blue-200 px-3 py-2"
          />
        </div>
      </div>
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>Maximum token</p>
          <p class="text-gray-600 text-sm">
            Set the maximum token generated by the AI
          </p>
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model.number="store.maxTokens"
            type="range"
            min="0"
            :max="maxTokensRange - 1"
            step="1"
            class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
          />
          <input
            v-model.number="store.maxTokens"
            type="number"
            class="w-20 rounded-md border border-blue-100 outline-blue-200 px-3 py-2"
          />
        </div>
      </div>
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>Presence Penalty</p>
          <p class="text-gray-600 text-sm">
            Positive values penalize new tokens based on whether they appear in
            the text so far, increasing the model's likelihood to talk about new
            topics.
          </p>
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model.number="store.presencePenalty"
            type="range"
            min="-2"
            max="2"
            step="0.01"
            class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
          />
          <input
            v-model.number="store.presencePenalty"
            type="number"
            class="w-20 rounded-md border border-blue-100 outline-blue-200 px-3 py-2"
          />
        </div>
      </div>
      <div>
        <div class="flex flex-col gap-1 mb-3">
          <p>Frequency Penalty</p>
          <p class="text-gray-600 text-sm">
            Positive values penalize new tokens based on their existing
            frequency in the text so far, decreasing the model's likelihood to
            repeat the same line verbatim.
          </p>
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model.number="store.frequencyPenalty"
            type="range"
            min="-2"
            max="2"
            step="0.01"
            class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
          />
          <input
            v-model.number="store.frequencyPenalty"
            type="number"
            class="w-20 rounded-md border border-blue-100 outline-blue-200 px-3 py-2"
          />
        </div>
      </div>
      <CButton @click="close"> Close </CButton>
    </div>
  </dialog>
</template>
