<script setup lang="ts">
import { ref, watch } from 'vue'

import CButton from './CButton.vue'
import { supportedModels, useChatGPTSetting } from '../store'

const props = defineProps<{
  open: boolean
}>()

const emit = defineEmits<(e: 'update:open', value: boolean) => void>()

const store = useChatGPTSetting()

const dialog = ref<HTMLDialogElement>()

const close = (): void => {
  emit('update:open', false)
}

watch(
  () => props.open,
  (value) => {
    if (value) {
      dialog.value?.showModal()
    } else {
      dialog.value?.close()
    }
  }
)
</script>
<template>
  <dialog ref="dialog" @close="$emit('update:open', false)" class="z-50 modal">
    <form method="dialog" class="modal-box">
      <div class="flex flex-col gap-3">
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Model</p>
            <p class="label-text-alt">The model to use for the AI</p>
          </div>
          <select
            :value="store.model"
            @change="
              (e) => store.setModel((e.target as HTMLSelectElement).value)
            "
            class="select select-bordered"
          >
            <option
              v-for="model in supportedModels"
              :key="model"
              :value="model"
            >
              {{ model }}
            </option>
          </select>
        </div>
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Use Function</p>
            <p class="label-text-alt">Utilize functions for ChatGPT</p>
          </div>

          <div class="flex items-center gap-3">
            <input
              v-model="store.useFunction"
              type="checkbox"
              class="checkbox"
            />
            {{ store.useFunction ? 'Enabled' : 'Disabled' }}
          </div>
        </div>
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Temperature</p>
            <p class="label-text-alt">
              The higher the temperature, the crazier the text
            </p>
          </div>
          <div class="flex items-center gap-3">
            <input
              v-model.number="store.temperature"
              type="range"
              min="0"
              max="2"
              step="0.01"
              class="range"
            />
            <input
              v-model="store.temperature"
              type="number"
              class="w-24 input input-bordered"
            />
          </div>
        </div>
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Maximum token</p>
            <p class="label-text-alt">
              Set the maximum token generated by the AI
            </p>
          </div>
          <div class="flex items-center gap-3">
            <input
              v-model.number="store.maxTokens"
              type="range"
              min="0"
              :max="store.maxSupportedTokens - 1"
              step="1"
              class="range"
            />
            <input
              v-model.number="store.maxTokens"
              type="number"
              class="w-24 input input-bordered"
            />
          </div>
        </div>
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Presence Penalty</p>
          </div>
          <div class="flex items-center gap-3">
            <input
              v-model.number="store.presencePenalty"
              type="range"
              min="-2"
              max="2"
              step="0.01"
              class="range"
            />
            <input
              v-model.number="store.presencePenalty"
              type="number"
              class="w-24 input input-bordered"
            />
          </div>
          <div class="label">
            <p class="label-text-alt">
              Positive values penalize new tokens based on whether they appear
              in the text so far, increasing the model's likelihood to talk
              about new topics.
            </p>
          </div>
        </div>
        <div class="form-control w-full">
          <div class="label">
            <p class="label-text">Frequency Penalty</p>
          </div>
          <div class="flex items-center gap-3">
            <input
              v-model.number="store.frequencyPenalty"
              type="range"
              min="-2"
              max="2"
              step="0.01"
              class="range"
            />
            <input
              v-model.number="store.frequencyPenalty"
              type="number"
              class="w-24 input input-bordered"
            />
          </div>
          <div class="label">
            <p class="label-text-alt">
              Positive values penalize new tokens based on their existing
              frequency in the text so far, decreasing the model's likelihood to
              repeat the same line verbatim.
            </p>
          </div>
        </div>
        <div class="modal-action">
          <CButton @click="close"> Close </CButton>
        </div>
      </div>
    </form>
  </dialog>
</template>
